### PR TITLE
Korawat_Checked

### PR DESCRIPTION
**Pull request by korawatt**
Add my user and my emoicon

## Objective

_Note why you're making this change and any relevant issues_
_Checked myself_

## Changes made

_Note what you actual changes you're proposing_ 
_Add my emoji and add my username_

## Who needs to review this Pull Request? 

_@mention some teammates who will check your Pull Request for any mistakes._
_Teammates, leave comments in a review if you approve this change_
@ahurley7
@ChiomaEkedede

### CODE REVIEW

**Comment by ChiomaEkedede** [comment]
👌🏽 great

**Review by ahurley7 — COMMENTED** [review]
remove dot in name

**Comment by ahurley7** [comment]
👍  Checked by Andrew Hurley @ahurley7

**Review by ahurley7 — APPROVED** [review]
👍  Validated

**Review by SophonWhisperer — APPROVED** [review]

**Pull request merged**
