### PR TITLE
modifying my name

### PR DESCRIPTION
**Pull request by joewadcan**
## Objective

Doing what i was told

## Changes made

_Note what you actual changes you're proposing_ 

## Who needs to review this Pull Request? 

_@mention some teammates who will check your Pull Request for any mistakes._
_Teammates, leave comments in a review if you approve this change_

### CODE REVIEW

**Comment by joewadcan** [comment]
@akingjr059 hey can you review this

**Comment by martinplima** [comment]
amazing contribution @joewadcan ! 😮

**Comment by lemonduckie** [comment]
I thought I committed but it doesn't show in the pull request :(

**Comment by martinplima** [comment]
> I thought I committed but it doesn't show in the pull request :(

Me too, can't find it anywhere

**Pull request closed without merging**
