### PR TITLE
Update readme.md

### PR DESCRIPTION
**Pull request by kyledeshon**
@Craig-KC

## Objective

_Note why you're making this change and any relevant issues_

## Changes made

_Note what you actual changes you're proposing_ 

## Who needs to review this Pull Request? 

_@mention some teammates who will check your Pull Request for any mistakes._
_Teammates, leave comments in a review if you approve this change_

### CODE REVIEW

**Comment by craig-kc** [comment]
Looks good! 👏

**Review by SophonWhisperer — CHANGES_REQUESTED** [review]
Hi @kyledeshon  - your username is incorrect in the pull request. Could you please change to kyledeshon ?

**Comment by SophonWhisperer** [comment]
Hey @kyledeshon  - thanks for updating the username. However, Github usernames are case sensitive. Can you change it from KyleDeshon to kyledeshon?

**Comment by kyledeshon** [comment]
@aparnachaganty Sorry about that! I updated it to be all lower case.

**Review by SophonWhisperer — APPROVED** [review]

**Pull request merged**
