### PR TITLE
Update readme.md

### PR DESCRIPTION
**Pull request by kichimori**
Edited my info
@aparnachaganty 

## Objective

_Note why you're making this change and any relevant issues_

## Changes made

_Note what you actual changes you're proposing_ 

## Who needs to review this Pull Request? 

_@mention some teammates who will check your Pull Request for any mistakes._
_Teammates, leave comments in a review if you approve this change_

### CODE REVIEW

**Comment by kichimori** [comment]
Can either of you help me collect 👍? Thanks! @cheriekwok and @josephyuberkeley

**Comment by cheriekwok** [comment]
It says I don't have write access to merge the pull request!

**Review by stehsieh — APPROVED** [review]
The change looks correct to me! 👍

**Review by SophonWhisperer — APPROVED** [review]

**Comment by kichimori** [comment]
Thank you both! @cheriekwok @stehsieh

**Pull request merged**
