### PR TITLE
updated_readme.md_Joe_Choi_(boncobee)

### PR DESCRIPTION
**Pull request by boncobee**
Respectfully asking for a +1 like:

@michaeljenkins88
@valenciamontoya
@jravellana
@OxfordOutlander

### CODE REVIEW

**Comment by jravellana** [comment]
+100

**Comment by valenciamontoya** [comment]
+1

**Comment by joewadcan** [comment]
Seeing alot of 👍🏽s but the submission doesn't have a GitHub username @boncobee - please add another commit to this Pull request

**Comment by boncobee** [comment]
Sorry about that! I believe I resubmitted another poll request labeled as:

Update_readme.md_second_try_Joe_Choi_boncobee

(Not 100% sure if that submission was done correctly though?

**Pull request merged**
