### PR TITLE
Update readme.md (@tiffany-shumate)

### PR DESCRIPTION
**Pull request by Tiffany-Shumate**
## Objective

_Note why you're making this change and any relevant issues_
Updating my name!

## Changes made

_Note what you actual changes you're proposing_ 

## Who needs to review this Pull Request? 

_@mention some teammates who will check your Pull Request for any mistakes._
_Teammates, leave comments in a review if you approve this change_
@aparnachaganty

### CODE REVIEW

**Comment by SophonWhisperer** [comment]
@Tiffany-Shumate  - There is one task pending - you need to have someone in the class review the PR and give a thumbs up. After that I’ll be able to merge the PR.

**Comment by SophonWhisperer** [comment]
@Tiffany-Shumate Additionally - the username is case-sensitive in Github. Please change make the change in the file to say 'Tiffany-Shumate' (which is your github username) rather than 'tiffany-shumate' (the username you've put in the file). I can merge after that.

**Review by SophonWhisperer — CHANGES_REQUESTED** [review]
please read comments on changes requested.

**Review by joewadcan — APPROVED** [review]
I worked with Tiffany 1:1 for this PR, so must have missed the capitalization. Just made the change on this PR so good to merge

**Comment by Tiffany-Shumate** [comment]
hello! @aparnachaganty am I set?

**Pull request merged**
