### PR TITLE
Update readme.md (Anupam Soni)

### PR DESCRIPTION
**Pull request by anupamsoni123**
Please approve!

## Objective

_Note why you're making this change and any relevant issues_

## Changes made

_Note what you actual changes you're proposing_ 

## Who needs to review this Pull Request? 

_@mention some teammates who will check your Pull Request for any mistakes._
_Teammates, leave comments in a review if you approve this change_

### CODE REVIEW

**Comment by ab-shrestha** [comment]
I am AB Shrestha and I approve the changes.

**Comment by SealaneC** [comment]
This is Charles, I approve the pull request 💯

**Comment by joewadcan** [comment]
> This is Charles, I approve the pull request 💯



> I am AB Shrestha and I approve the changes.

Both approvals here but this PR is missing the github user name. Can't merge.

**Comment by anupamsoni123** [comment]
Hi Joe,

Hope you are well! I had an updated request sent a few minutes after since the github username was missing from the first pull request. Could you please confirm?

**Comment by anupamsoni123** [comment]
Hi Joe,

Hope you are well! I had an updated request sent a few minutes after since
the github username was missing from the first pull request.
Could you please confirm?

**Comment by anupamsoni123** [comment]
Hi Joe,

Hope you are well! I had an updated request sent a few minutes after since
the github username was missing from the first pull request.
Could you please confirm?
Named: "Update readme.md (Anupam Soni - updated)"

**Comment by jainaman93** [comment]
@anupamsoni123 : please close this duplicate request

**Pull request closed without merging**
