### PR TITLE
Update @alejandravl readme.md

### PR DESCRIPTION
**Pull request by alejandravl**
## Objective

_changing my name from the list to get the hw done!

## Changes made

_changing my name detail

## Who needs to review this Pull Request? 

_@arontheising check this out!

### CODE REVIEW

**Comment by g7lewis** [comment]
👌

**Comment by arontheising** [comment]
this is terrific and you deserve an award or a trophy.

**Comment by stalerat** [comment]
Hey @alejandravl, this PR looks great. Could you please also add your nickname?

**Comment by alejandravl** [comment]
> Hey @alejandravl, this PR looks great. Could you please also add your nickname?

Yes! LMK if all good now @stalerat

**Pull request merged**
