### PR TITLE
Checking off Nisha Garg as done!

### PR DESCRIPTION
**Pull request by ng2217**

### CODE REVIEW

**Review by henriquedc1 — CHANGES_REQUESTED** [review]
@ng2217, I need you to remove Nao's changes from your commits on this PR. Right now, you are including his changes to your PR, which generates a conflict on the master branch.

**Comment by ng2217** [comment]
Removed Nao's changes from my commits on this PR to solve conflict on the master branch.

**Review by henriquedc1 — CHANGES_REQUESTED** [review]
Good job, Nisha! Nao's name was successfully removed from you PR! Now we only need one more thing for you to get it 100% right: make sure to add an "@" and your username in parenthesis after your name (check joe's example as a reference)

**Comment by ng2217** [comment]
Closing this request as a new one has been established.

**Pull request closed without merging**
