### PR TITLE
Update readme.md- sharpaero

### PR DESCRIPTION
**Pull request by sharpaero**
## Objective

_Note why you're making this change and any relevant issues_
Check off my name and learn pull requests in git

## Changes made
checked off my name

_Note what you actual changes you're proposing_ 
line 200 

## Who needs to review this Pull Request? 

_@mention some teammates who will check your Pull Request for any mistakes._

@aywang
@caroline-tsoi
@sharpaero

_Teammates, leave comments in a review if you approve this change_

### CODE REVIEW

**Comment by caroline-tsoi** [comment]
Looks good!

**Comment by stalerat** [comment]
Hey @sharpaero , this PR looks great. Could you please add your nickname?

**Comment by sharpaero** [comment]
@stalerat not sure where else I need to add a nickname?

**Review by sharpaero — COMMENTED** [review]
@stalerat - updated with username in list

**Pull request merged**
