### PR TITLE
Update readme.md

### PR DESCRIPTION
**Pull request by cailintodd**
Changed Mine-CT

## Objective

_Note why you're making this change and any relevant issues_

## Changes made

_Note what you actual changes you're proposing_ 

## Who needs to review this Pull Request? 

_@mention some teammates who will check your Pull Request for any mistakes._
_Teammates, leave comments in a review if you approve this change_

### CODE REVIEW

**Comment by stalerat** [comment]
Hey @cailintodd , this PR looks great. Could you please add your nickname and some emoji?

**Comment by cailintodd** [comment]
Hi! I think I added an emoji and nickname. Let me know if it does not show up.

**Comment by cailintodd** [comment]
HI @stalerat - let me know if this looks good based on feedback!

**Comment by stalerat** [comment]
Closing this PR since another PR was already merged.

**Pull request closed without merging**
