### PR TITLE
Update readme.md

### PR DESCRIPTION
**Pull request by dcerda9**
## Objective

To update username for Daniel

## Changes made

Adding username and Emoji

## Who needs to review this Pull Request? 

@stalerat 

_@mention some teammates who will check your Pull Request for any mistakes._
@boncobee @ojinchunk

### CODE REVIEW

**Comment by boncobee** [comment]
+1

**Comment by wkellogg** [comment]
+1

**Comment by fedepacheco** [comment]
+1

**Comment by ojinchunk** [comment]
+3000

because I love you 3000

**Pull request merged**
