### PR TITLE
Update please!

### PR DESCRIPTION
**Pull request by eringums**
@joewadcan I proposed an update to the file. Thanks!

### CODE REVIEW

**Comment by joewadcan** [comment]
@eringums did you mean  🌴  `:palm_tree:` instead ?

**Comment by eringums** [comment]
Sure did! I'll update it.

**Review by eringums — COMMENTED** [review]
@joewadcan updated, thanks!

**Comment by joewadcan** [comment]
Looks great @eringums 🌴 😎 🌴  !

**Pull request merged**
