### PR TITLE
Edited Joshua Chang

### PR DESCRIPTION
**Pull request by airchang78**
## Objective

Part 1 GitHub assignment

## Changes made

Followed instructions

## Who needs to review this Pull Request? 

@daikitakai

### CODE REVIEW

**Comment by wayne0933** [comment]
nice nice nice nice nice nice nice nice nice nice nice nice nice nice nice nice nice nice nice nice nice nice nice nice nice nice nice nice nice nice nice nice nice nice nice nice nice nice nice nice nice nice nice nice nice nice nice nice nice nice nice nice nice nice nice nice nice nice nice nice nice nice nice nice nice nice nice nice nice nice nice nice nice nice nice nice nice nice nice nice nice nice nice nice nice nice nice nice nice nice nice nice nice nice nice nice nice nice nice nice nice nice nice nice nice nice nice nice nice nice nice nice nice nice nice nice nice nice nice nice nice nice nice nice nice nice nice nice nice nice nice nice nice nice nice nice nice nice nice nice nice nice nice nice nice nice nice nice nice nice nice nice nice nice nice nice

**Comment by airchang78** [comment]
@wayne0933 thumbs up me

**Comment by wayne0933** [comment]
approve approve approve approve approve approve approve approve approve approve approve approve approve approve approve approve approve approve approve approve approve approve approve approve approve approve approve approve approve approve approve

**Comment by airchang78** [comment]
👍

**Pull request merged**
