### PR TITLE
Sebastian.Changes

### PR DESCRIPTION
**Pull request by skrappe12-berk**
Checked my name, added username, and added emojis

## Objective

Updating information for assignment

## Changes made

checked my name, added username, added emojis

## Who needs to review this Pull Request? 

@joewadcan

### CODE REVIEW

**Comment by b-supriya-reddy** [comment]
everything looks great. 
please tag a classmate(not Joe or me) in the comments and ask them to approve the PR

**Comment by skrappe12-berk** [comment]
@gonzalovn93 Can you please approve? Feel free to tag me and I'll review yours!

**Comment by b-supriya-reddy** [comment]
Please ask Gonzalo to approve your PR so that I can merge

**Comment by gonzalovn93** [comment]
@skrappe12-berk just got this, looks good!!

**Pull request merged**
