### PR TITLE
Update: Geo Guillen Added checkmark, username and emojis to file

### PR DESCRIPTION
**Pull request by geo8892**
## Objective

_Note why you're making this change and any relevant issues_

AssignmentC: Part1 - GitHub Assignment  - Geo Guillen

## Changes made

Added checkmark and username next to my listed name.

## Who needs to review this Pull Request? 

@joewadcan 

_@mention some teammates who will check your Pull Request for any mistakes._
_Teammates, leave comments in a review if you approve this change_

### CODE REVIEW

**Comment by stalerat** [comment]
Hey @geo8892 looks good! Could you please:
1) Add emoji next to your nickname
2) Mention several classmates so that they 👍  your commit

**Comment by FlyingOreo** [comment]
+1

**Comment by gdempse** [comment]
+1

**Comment by geo8892** [comment]
@stalerat 

1. Added. :)
2. On it!

Thank you 🔥🎧🎤 This is fun

**Pull request merged**
