### PR TITLE
Update readme.md

### PR DESCRIPTION
**Pull request by smallyn9**
## Objective

_Updated readme for Sevara_

## Changes made

_Updated the x, the emoji, and @_ 

## Who needs to review this Pull Request? 

_@mention some teammates who will check your Pull Request for any mistakes._
_Teammates, leave comments in a review if you approve this change_

### CODE REVIEW

**Comment by ChiomaEkedede** [comment]
🤝

**Review by spg222 — APPROVED** [review]
Good job!

**Review by SophonWhisperer — CHANGES_REQUESTED** [review]
@smallyn9  - Please update your pull request with the correct username i.e. smallyn9

**Comment by smallyn9** [comment]
@aparnachaganty Hi, I updated my username. Thanks for catching that!

**Review by SophonWhisperer — APPROVED** [review]

**Pull request merged**
