### PR TITLE
Oriana Chiu Readme Changes

### PR DESCRIPTION
**Pull request by FlyingOreo**
Approve meh!

### CODE REVIEW

**Comment by FlyingOreo** [comment]
@stalerat @gdempse @jhpark89

**Comment by jhpark89** [comment]
+1

**Comment by stalerat** [comment]
Hey @FlyingOreo great job so far. Could you please:
1) add some emoji next to your nickname
2) ask smb beside Jin to 👍 your commit

**Comment by gdempse** [comment]
+1

**Comment by geo8892** [comment]
+1 👍 @FlyingOreo

**Comment by joewadcan** [comment]
GReat job team!

**Pull request merged**
