### PR TITLE
Brian Zhu

### PR DESCRIPTION
**Pull request by BrianZhu-Berkeley**
AssignmentC: Part1 - GitHub Assignment

## Objective

_Note why you're making this change and any relevant issues_

## Changes made

_Note what you actual changes you're proposing_ 

## Who needs to review this Pull Request? 

_@mention some teammates who will check your Pull Request for any mistakes._
_Teammates, leave comments in a review if you approve this change_

### CODE REVIEW

**Review by unfollow11 — APPROVED** [review]

**Comment by unfollow11** [comment]
LGTM @BrianZhu-Berkeley

**Comment by b-supriya-reddy** [comment]
use @ and add your github username to the code

**Comment by b-supriya-reddy** [comment]
Also, use @ to tag a person in the comments and then get their approval.

**Comment by BrianZhu-Berkeley** [comment]
@b-supriya-reddy changes have been made, please review and advise. Thank you.

**Pull request merged**
