### PR TITLE
Jonas Linde Updates readme.md

### PR DESCRIPTION
**Pull request by gitjl22**
I think I did it? 

## Objective

Fulfill the assignment!

## Changes made

Checked my name using an X

## Who needs to review this Pull Request? 
@joewadcan
@arontheising
_@mention some teammates who will check your Pull Request for any mistakes._
_Teammates, leave comments in a review if you approve this change_

### CODE REVIEW

**Comment by arontheising** [comment]
LGTM

**Comment by Aleixsc** [comment]
LGTM man

**Comment by stalerat** [comment]
Hey @gitjl22  , this PR looks great. Could you please add your nickname and some emoji?

**Comment by gitjl22** [comment]
@stalerat I think I fixed it. Not sure if a pull request was sent.

**Pull request merged**
