### PR TITLE
X added in bracket next to Kristen Hayashi

### PR DESCRIPTION
**Pull request by Gityashi**
👀 Who wants to check this out

## Who needs to review this Pull Request? 

@Anna586 and @stalerat  Please check this out 🙈

### CODE REVIEW

**Comment by anna586** [comment]
🙉 I approve this change @Gityashi

**Review by Gityashi — COMMENTED** [review]
Realized I didn't add my username & emoji - updated again

**Review by mcroeller1 — APPROVED** [review]

**Comment by mcroeller1** [comment]
Ship it 🚢

**Comment by Gityashi** [comment]
@stalerat Is this good to merge now?  It's been updated & approved by my partner.

**Comment by stalerat** [comment]
@Gityashi yes, it's perfect.

**Pull request merged**
