### PR TITLE
added uri names

### PR DESCRIPTION
**Pull request by URIELGSN**
## Objective

better readme

## Changes made

Added x to Uriel Greenstein name and emoji

## Who needs to review this Pull Request? 
anyone

_@mention some teammates who will check your Pull Request for any mistakes._
_Teammates, leave comments in a review if you approve this change_

### CODE REVIEW

**Comment by wesleysfng** [comment]
wow so amazing 👍

**Comment by solelibedinskyale** [comment]
great job uri!

**Review by SophonWhisperer — CHANGES_REQUESTED** [review]
@URIELGSN  - Please update username as URIELGSN. Github usernames are case-sensitive.

**Comment by SophonWhisperer** [comment]
Closing as it is a duplicate

**Pull request closed without merging**
