### PR TITLE
updated github name

### PR DESCRIPTION
**Pull request by Flowerandsalt**
used @ to add my github name

## Objective

_Note why you're making this change and any relevant issues_

## Changes made

_Note what you actual changes you're proposing_ 

## Who needs to review this Pull Request? 

_@mention some teammates who will check your Pull Request for any mistakes._
_Teammates, leave comments in a review if you approve this change_

### CODE REVIEW

**Comment by b-supriya-reddy** [comment]
everything looks great. 

Tag a classmate in the comment and get their approval.

**Comment by Flowerandsalt** [comment]
@gonzalovn93 Hi Gonzalo, would you mind approving this one for me? Thank you!

**Comment by b-supriya-reddy** [comment]
Please ask Gonzalo to approve your PR so that I can merge

**Comment by Flowerandsalt** [comment]
@gonzalovn93 Hi Gonzalo, can you please approve this PR? Thanks!

**Comment by gonzalovn93** [comment]
@Flowerandsalt just checked, looks good!

**Pull request merged**
