### PR TITLE
Update readme.md

### PR DESCRIPTION
**Pull request by wkellogg**
@tmullin-1
@fedepacheco
@sochoteco
@anjuved

### CODE REVIEW

**Review by tmullin-1 — APPROVED** [review]
Literally the single greatest thing to ever happen to coding

**Review by fedepacheco — COMMENTED** [review]
This is gorgeous! 🥇

**Review by sochoteco — APPROVED** [review]

**Review by fedepacheco — APPROVED** [review]
Impressive!

**Comment by stalerat** [comment]
hey @wkellogg could you please add some emoji after your nickname?

**Pull request merged**
