### PR TITLE
Updated file readme.md

### PR DESCRIPTION
**Pull request by BasimSiddiqui**
## Objective

_Note why you're making this change and any relevant issues_

## Changes made

_Note what you actual changes you're proposing_ 

## Who needs to review this Pull Request? 
@dbadih

### CODE REVIEW

**Comment by dbadih** [comment]
+1

**Review by SophonWhisperer — CHANGES_REQUESTED** [review]
@BasimSiddiqui  - Please update the PR with the username as well. Currently the PR is missing your username.

**Comment by joewadcan** [comment]
@BasimSiddiqui we're still waiting on you to edit this Pull Request so it can be merged. Please do so by Wednesday March 1st, or it will be considered late.

**Comment by BasimSiddiqui** [comment]
Thanks for highlighting. I have made the changes now.

**Review by SophonWhisperer — APPROVED** [review]

**Pull request merged**
