### PR TITLE
Update readme.md

### PR DESCRIPTION
**Pull request by Amayesing**
## Objective

Updated with my name @Amayesing

## Changes made

_Note what you actual changes you're proposing_ 

## Who needs to review this Pull Request? 

@stalerat

### CODE REVIEW

**Comment by Amayesing** [comment]
@stalerat

**Comment by stalerat** [comment]
Hey @Amayesing , this PR looks great. Could you ask smb to 👍 it?

**Comment by Amayesing** [comment]
@dpanic286  @CorrineMarquardt

**Comment by dpanic286** [comment]
Looks great! Ready to 🚢

**Pull request merged**
