### PR TITLE
update for Valerie

### PR DESCRIPTION
**Pull request by vhuang13**
@stalerat @d27-c @thaisesteves

## Objective

_Note why you're making this change and any relevant issues_

## Changes made

_Note what you actual changes you're proposing_ 

## Who needs to review this Pull Request? 

_@mention some teammates who will check your Pull Request for any mistakes._
_Teammates, leave comments in a review if you approve this change_

### CODE REVIEW

**Comment by d27-c** [comment]
+1!!

**Comment by stalerat** [comment]
Hey @vhuang13 great job! You need just one more 👍

**Comment by vhuang13** [comment]
@lucassea Can you help me with this? Thanks!

**Comment by lucassea** [comment]
@vhuang13 congrats!

**Pull request merged**
