### PR TITLE
Aleix ticked name

### PR DESCRIPTION
**Pull request by Aleixsc**
## Objective

As part os the Intro to coding class 6

## Changes made

I added a tick next to my name "Aleix"

## Who needs to review this Pull Request? 
@joewadcan @justinli90 @ccastilloux @gitjl22
_Teammates, leave comments in a review if you approve this change_

### CODE REVIEW

**Comment by ccastilloux** [comment]
Approved

**Comment by gitjl22** [comment]
Very talented developer. 10/10.

**Comment by stalerat** [comment]
Hey @Aleixsc , this PR looks great. Could you please add your nickname and some emoji?

**Comment by Aleixsc** [comment]
Can I modify it from this thread?
Or I have to go through the same process again?
@stalerat

**Comment by stalerat** [comment]
@Aleixsc you can make one more commit within this pull request. The new commit would be on top of the first one.

**Comment by Aleixsc** [comment]
@stalerat @joewadcan  Should have a couple of emojis now

**Comment by stalerat** [comment]
Thanks, it's perfect! @Aleixsc

**Pull request merged**
