### PR TITLE
Update readme.md

### PR DESCRIPTION
**Pull request by tai-wu**
by Tai Wu

## Objective

_Note why you're making this change and any relevant issues_

## Changes made

_Note what you actual changes you're proposing_ 

## Who needs to review this Pull Request? 

@cailintodd, @gwrightsimmons-haas, @Aloha15, @fcovarr1, can you give me some love (e.g., comments, emojis)? Had to add my GitHub username and an emoji in the latest update. Thanks, team.

### CODE REVIEW

**Comment by cailintodd** [comment]
Looks good, Tai!

**Comment by stalerat** [comment]
Hey @tai-wu , this looks great! Could you please also add your Github nickname and some emoji?

**Review by tai-wu — COMMENTED** [review]
@stalerat , Daniil let me know if there is anything else missing. Thank you!

**Comment by tai-wu** [comment]
> Hey @tai-wu , this looks great! Could you please also add your Github nickname and some emoji?

Of course. Thanks for your prompt review!

**Pull request merged**
