### PR TITLE
Update for Cristobal Escobar

### PR DESCRIPTION
**Pull request by cristobalescobar**
@stalerat I updated my emoji and nickname! :)

## Objective

_Note why you're making this change and any relevant issues_

## Changes made

_Note what you actual changes you're proposing_ 

@sochoteco 

_@mention some teammates who will check your Pull Request for any mistakes._
_Teammates, leave comments in a review if you approve this change_

### CODE REVIEW

**Comment by sochoteco** [comment]
+1

**Comment by m-mamer** [comment]
+1

**Comment by boncobee** [comment]
+1

**Comment by fedepacheco** [comment]
+1 awesome!

**Pull request merged**
