### PR TITLE
Updated Una Kim! 🏆

### PR DESCRIPTION
**Pull request by unakim**
Completed assignment: 
1 - checked off my name
2 - added my username
3 - added two emojis

🏆🏆🏆🏆🏆🏆🏆🏆

Next steps: @joewadcan or @stalerat to approve and merge my changes.

Request for +1:
@AngusMaguir3
@dhruvkc
@lucassea

### CODE REVIEW

**Comment by AngusMaguir3** [comment]
This looks great! 🏆

**Comment by lucassea** [comment]
Here

**Comment by dhruvkc** [comment]
+1 let's do this

**Comment by d27-c** [comment]
++

**Pull request merged**
