### PR TITLE
Update readme.md

### PR DESCRIPTION
**Pull request by mcroeller1**
Added an X next to my name (Maria Roller) although my name is Maria Carolina Roller :)

## Objective

_Note why you're making this change and any relevant issues_

I want to get the points for my assignment :)

## Changes made

_Note what you actual changes you're proposing_ 

I put an x next to my name

## Who needs to review this Pull Request? 

_@mention some teammates who will check your Pull Request for any mistakes._
_Teammates, leave comments in a review if you approve this change_

@gityashi please approve
@stalerat

### CODE REVIEW

**Comment by Gityashi** [comment]
SHIP IT 🚢

**Comment by nbretschneider** [comment]
Gute Arbeit, Ship It!

**Comment by Gityashi** [comment]
@mcroeller1 OOPS Said ship it too early.  Also need to add your username & emoji to the code, not just the X

**Comment by mcroeller1** [comment]
@Gityashi added my username and emoji!

**Comment by mcroeller1** [comment]
@Gityashi added my @ sign!

**Review by Gityashi — APPROVED** [review]
Looks good now! 👍

**Pull request merged**
