### PR TITLE
Update readme.md

### PR DESCRIPTION
**Pull request by kfrank249**
## Objective

Add check and user name

## Changes made

Add check and insert GitHub name

## Who needs to review this Pull Request? 

Someone in the class

### CODE REVIEW

**Comment by b-supriya-reddy** [comment]
- add a teammate's name in comments and get their approval
- use @ to add your github name
- use : to add an emoji

**Comment by kfrank249** [comment]
@danica384 can you please approve my addition? Thanks!

**Review by Danica384 — APPROVED** [review]
Approved

**Comment by b-supriya-reddy** [comment]
you still have to do these changes and update the pull request 

use @ to add your github name
use : to add an emoji

**Comment by b-supriya-reddy** [comment]
Still have to add your emoji; also use @ to add your github user name

**Comment by b-supriya-reddy** [comment]
duplicate PR

**Pull request closed without merging**
