### PR TITLE
Add Lijun Shen

### PR DESCRIPTION
**Pull request by unfollow11**
For assignment

## Objective

_Note why you're making this change and any relevant issues_

## Changes made

_Note what you actual changes you're proposing_ 

## Who needs to review this Pull Request? 

_@mention some teammates who will check your Pull Request for any mistakes._
_Teammates, leave comments in a review if you approve this change_

### CODE REVIEW

**Review by BrianZhu-Berkeley — APPROVED** [review]
Good to go @unfollow11

**Comment by b-supriya-reddy** [comment]
use @ and add your github username to the code 
use @ and add a classmate in the comments and then get their approval

**Comment by unfollow11** [comment]
@b-supriya-reddy can you please review and approve my change? 

Sorry is that what you mean?

**Comment by b-supriya-reddy** [comment]
No, you have to add your username to the code using @. check what others have done or join the office hours now(in the next 45 min)

**Comment by unfollow11** [comment]
@b-supriya-reddy I have made the change, let me know if it's good to go. Thanks

**Pull request merged**
