### PR TITLE
Update readme.md

### PR DESCRIPTION
**Pull request by Daiki1992**
## Objective

_Note why you're making this change and any relevant issues_

## Changes made

_Note what you actual changes you're proposing_ 

## Who needs to review this Pull Request? 

_@mention some teammates who will check your Pull Request for any mistakes._
_Teammates, leave comments in a review if you approve this change_

### CODE REVIEW

**Comment by Daiki1992** [comment]
@wayne0933

**Comment by wayne0933** [comment]
approve 👎

**Comment by AJHutchinson09** [comment]
Make sure you remember to include your GitHub username @Daiki1992

**Comment by b-supriya-reddy** [comment]
use @ and add your username to the code

**Comment by Daiki1992** [comment]
I think I have added my username but does that look good now? @b-supriya-reddy

**Pull request merged**
