### PR TITLE
Update readme.md

### PR DESCRIPTION
**Pull request by jeffcc412**
Checking off my name (JC Chen) and adding username with emoji

## Objective

_Note why you're making this change and any relevant issues_

## Changes made

_Note what you actual changes you're proposing_ 

## Who needs to review this Pull Request? 

_@mention some teammates who will check your Pull Request for any mistakes._
_Teammates, leave comments in a review if you approve this change_

### CODE REVIEW

**Comment by b-supriya-reddy** [comment]
- mention a teammate in comments and get their approval
- use @ to add your github user name

**Comment by jeffcc412** [comment]
@gonzalovn93

**Review by Flowerandsalt — APPROVED** [review]
Looks good to me!

**Comment by gonzalovn93** [comment]
Looks good JC!

**Comment by b-supriya-reddy** [comment]
still have to do this - use @ to add your github user name

**Comment by Flowerandsalt** [comment]
Thanks Supriya for the reminder! Just added @ to my user name.

Scarlet

**Comment by gonzalovn93** [comment]
Looks good Scarlet

**Comment by jeffcc412** [comment]
@b-supriya-reddy just updated

**Pull request merged**
