### PR TITLE
Update readme.md - ali nanji

### PR DESCRIPTION
**Pull request by alinanji831**
## Objective

Checking off my name.

## Changes made
Checked off my name and added emojis 

## Who needs to review this Pull Request? 

@joewadcan

### CODE REVIEW

**Comment by jainaman93** [comment]
@alinanji831: please add "@" before your profile name. Look at Joe's example

**Comment by alinanji831** [comment]
@jainaman93 Done!

**Comment by jainaman93** [comment]
@alinanji831 : ask for approval

**Comment by alinanji831** [comment]
> @alinanji831 : ask for approval

@lizhen639   Please approve

**Comment by lizhen639** [comment]
I approve!

**Pull request merged**
