### PR TITLE
Update readme.md

### PR DESCRIPTION
**Pull request by valenciamontoya**

### CODE REVIEW

**Comment by valenciamontoya** [comment]
@stalerat  @jravellana @michaeljenkins88 @boncobee @davideisenman @joewadcan

**Comment by boncobee** [comment]
+1

**Comment by valenciamontoya** [comment]
@OxfordOutlander
@michaeljenkins88 
@boncobee 
@joewadcan 
@stalerat 
@jravellana

**Comment by stalerat** [comment]
Hey @valenciamontoya , could you please also add your nickname before emoji? Besides that commit looks great!

**Comment by joewadcan** [comment]
great job team !

**Pull request merged**
